ALTER TABLE courses
    ADD COLUMN rejection_reason VARCHAR(1000);

UPDATE courses
SET status = 'PENDING_REVIEW'
WHERE status = 'PENDING';

CREATE TABLE exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    question VARCHAR(1000) NOT NULL,
    answer_options TEXT,
    correct_answer VARCHAR(1000) NOT NULL,
    explanation VARCHAR(1000),
    order_index INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_exercises_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE
);

CREATE TABLE exercise_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    answer VARCHAR(1000) NOT NULL,
    correct BOOLEAN NOT NULL,
    attempted_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_exercise_attempts_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_exercise_attempts_exercise FOREIGN KEY (exercise_id) REFERENCES exercises (id) ON DELETE CASCADE
);

CREATE TABLE reading_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    language VARCHAR(50) NOT NULL,
    level VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    creator_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reading_materials_creator FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_one_id BIGINT NOT NULL,
    participant_two_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_conversations_participants UNIQUE (participant_one_id, participant_two_id),
    CONSTRAINT fk_conversations_participant_one FOREIGN KEY (participant_one_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversations_participant_two FOREIGN KEY (participant_two_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    sent_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_exercises_lesson_id ON exercises (lesson_id);
CREATE INDEX idx_exercise_attempts_student_id ON exercise_attempts (student_id);
CREATE INDEX idx_exercise_attempts_exercise_id ON exercise_attempts (exercise_id);
CREATE INDEX idx_reading_materials_language_level ON reading_materials (language, level);
CREATE INDEX idx_conversations_participant_one_id ON conversations (participant_one_id);
CREATE INDEX idx_conversations_participant_two_id ON conversations (participant_two_id);
CREATE INDEX idx_messages_conversation_id ON messages (conversation_id);
CREATE INDEX idx_messages_sender_id ON messages (sender_id);
