CREATE TABLE personal_dictionaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_personal_dictionaries_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE dictionary_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_word VARCHAR(200) NOT NULL,
    target_word VARCHAR(200) NOT NULL,
    dictionary_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_dictionary_entries_dictionary FOREIGN KEY (dictionary_id) REFERENCES personal_dictionaries (id) ON DELETE CASCADE
);

CREATE INDEX idx_personal_dictionaries_user_id ON personal_dictionaries (user_id);
CREATE INDEX idx_dictionary_entries_dictionary_id ON dictionary_entries (dictionary_id);
