CREATE TABLE analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    lesson_id BIGINT,
    exercise_id BIGINT,
    event_type VARCHAR(50) NOT NULL,
    correct BOOLEAN,
    duration_seconds BIGINT,
    metadata TEXT,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_analytics_events_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_analytics_events_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_analytics_events_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE SET NULL,
    CONSTRAINT fk_analytics_events_exercise FOREIGN KEY (exercise_id) REFERENCES exercises (id) ON DELETE SET NULL
);

CREATE INDEX idx_analytics_events_course_time ON analytics_events (course_id, occurred_at);
CREATE INDEX idx_analytics_events_course_type_time ON analytics_events (course_id, event_type, occurred_at);
CREATE INDEX idx_analytics_events_user_course_time ON analytics_events (user_id, course_id, occurred_at);
CREATE INDEX idx_analytics_events_lesson ON analytics_events (lesson_id);
CREATE INDEX idx_analytics_events_exercise ON analytics_events (exercise_id);
